name: hestia

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.3.2
  equatable: ^2.0.3
  flutter_secure_storage: ^6.1.0
  local_auth: ^2.1.2
  local_auth_android: ^1.0.21
  image_picker: ^0.8.7+1
  path_provider: ^2.0.14
  provider: ^6.0.5
  auto_route: ^7.0.0
  transparent_image: ^2.0.0
  flutter_bloc: ^8.1.2
  ws: ^0.1.2
  rxdart: ^0.27.7
  dio: ^5.0.3
  syncfusion_flutter_charts: ^21.1.37
  shimmer_animation: ^2.1.0+1
  drift: ^2.7.0
  sqlite3_flutter_libs: ^0.5.0
  redux: ^5.0.0
  elementary: ^3.0.0
  elementary_helper: ^1.0.1
  json_serializable: ^6.7.1
  json_annotation: ^4.8.1
  retrofit: 4.0.3
  pretty_dio_logger: ^1.3.1

  freezed_annotation: 
  path:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  auto_route_generator: 
  build_runner: ^2.3.3
  drift_dev: ^2.7.0
  elementary_test: ^2.0.0
  retrofit_generator: ^8.0.6
  freezed: 

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/auth/
    - assets/main/

  fonts:
   - family: Lexend
     fonts:
       - asset: fonts/Lexend-Regular.ttf
       - asset: fonts/Lexend-Bold.ttf
         weight: 700
   - family: Hestia Flame
     fonts:
       - asset: fonts/HestiaFlame.ttf  
